// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttglcxuznhhcdnuyxhqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Z2xjeHV6bmhoY2RudXl4aHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDQ4OTQsImV4cCI6MjA2NjQyMDg5NH0.i3eGVRFuVBWl1eQa0LQg4wm_VTIe2cZByYvTdCF14pE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);